In [72]:
cd /content/drive/My Drive/Gender Classification

/content/drive/My Drive/Gender Classification


In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [0]:
!unzip 13_7651_compressed_NationalNames.csv.zip

Archive:  13_7651_compressed_NationalNames.csv.zip
replace NationalNames.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: n


In [0]:
import numpy as np
import pandas as pd


In [0]:
dataset1=pd.read_csv('NationalNames.csv')
dataset2=pd.read_csv('name.csv')
dataset3=pd.read_csv('indiannames.csv')
dataset4=pd.read_csv('nam.csv')
dataset5=pd.read_csv('SSA_Names.csv')

In [0]:
dataset1=dataset1.loc[:,['Name','Gender']]
dataset2=dataset2.loc[:,['Name','Gender']]
dataset3=dataset3.loc[:,['Name','Gender']]
dataset4=dataset4.loc[:,['Name','Gender']]
dataset5=dataset5.loc[:,['Name','Gender']]



In [0]:
data=pd.concat([dataset1,dataset2,dataset3,dataset4,dataset5])

In [0]:
data=data.reset_index()

In [0]:
dataset=data.drop(['index'],axis=1)

In [131]:
dataset

Name Gender
0             Mary      F
1             Anna      F
2             Emma      F
3        Elizabeth      F
4           Minnie      F
...            ...    ...
1994026     Zykell      M
1994027     Zyking      M
1994028      Zykir      M
1994029      Zyrus      M
1994030       Zyus      M

[1994031 rows x 2 columns]

In [132]:
len(dataset['Name'].unique())

110000

In [0]:
dataset.drop_duplicates('Name',ignore_index=True,inplace=True)

In [134]:
dataset.isnull().values.any()

True

In [0]:
dataset=dataset.dropna()

In [136]:
dataset.isnull().values.any()

False

In [0]:
name=dataset['Name']

In [138]:
len(name.unique())

109999

In [0]:
name=list(name)

In [0]:
label=list(dataset['Gender'])

In [141]:
label

['F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F'

In [0]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [0]:
labels=le.fit_transform(label)

In [144]:
labels

array([0, 0, 0, ..., 0, 0, 0])

In [145]:
le.classes_

array(['F', 'M'], dtype='<U1')

In [0]:
from sklearn.feature_extraction.text import CountVectorizer

In [0]:
cv=CountVectorizer(analyzer='char')

In [0]:
names=cv.fit_transform(name).toarray()

In [149]:
len(names[1])

26

In [0]:
from sklearn.model_selection import train_test_split
feature_train,feature_test,label_train,label_test=train_test_split(names,labels,test_size=0.2,random_state=42)

In [151]:
from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB()
model.fit(feature_train,label_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [0]:
label_pred=model.predict(feature_test)

In [0]:
import sklearn.metrics as m

In [154]:
m.accuracy_score(label_test,label_pred)

0.6785909090909091

LSTM

In [0]:
from keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer(char_level=True)
tokenizer.fit_on_texts(name)
sequence_of_int = tokenizer.texts_to_sequences(name)


In [0]:
from keras.preprocessing.sequence import pad_sequences
padsequences=pad_sequences(sequence_of_int,maxlen=15,padding='post')

In [157]:
len(padsequences[2])

15

In [0]:
from keras.utils.np_utils import to_categorical
labels=to_categorical(labels)

In [0]:
from keras.models import Sequential
from keras.layers import Dense,LSTM,Embedding,Dropout

In [160]:
padsequences.shape

(109999, 15)

In [0]:
from sklearn.model_selection import train_test_split
feature_train,feature_test,label_train,label_test=train_test_split(padsequences,labels,test_size=0.1,random_state=42)

In [162]:
model=Sequential()
model.add(Embedding(26,64,input_length=15))
model.add(LSTM(2048,return_sequences=True))
model.add(LSTM(256,return_sequences=False))
model.add(Dropout(0.2))
model.add(Dense(2,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
model.summary()

Model: "sequential_9"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_3 (Embedding)      (None, 15, 64)            1664      
_________________________________________________________________
lstm_17 (LSTM)               (None, 15, 2048)          17309696  
_________________________________________________________________
lstm_18 (LSTM)               (None, 256)               2360320   
_________________________________________________________________
dropout_12 (Dropout)         (None, 256)               0         
_________________________________________________________________
dense_9 (Dense)              (None, 2)                 514       
Total params: 19,672,194
Trainable params: 19,672,194
Non-trainable params: 0
_________________________________________________________________


In [163]:
model.fit(feature_train,label_train,epochs=50,validation_data=(feature_test,label_test),batch_size=1000)


/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/indexed_slices.py:434: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "


Train on 98999 samples, validate on 11000 samples
Epoch 1/50
98999/98999 [==============================] - 32s 325us/step - loss: 0.5590 - accuracy: 0.7127 - val_loss: 0.4793 - val_accuracy: 0.7755
Epoch 2/50
98999/98999 [==============================] - 31s 317us/step - loss: 0.4414 - accuracy: 0.7971 - val_loss: 0.4246 - val_accuracy: 0.8062
Epoch 3/50
98999/98999 [==============================] - 31s 317us/step - loss: 0.4127 - accuracy: 0.8146 - val_loss: 0.4102 - val_accuracy: 0.8155
Epoch 4/50
98999/98999 [==============================] - 31s 318us/step - loss: 0.3996 - accuracy: 0.8215 - val_loss: 0.3990 - val_accuracy: 0.8245
Epoch 5/50
98999/98999 [==============================] - 31s 317us/step - loss: 0.3891 - accuracy: 0.8258 - val_loss: 0.3943 - val_accuracy: 0.8234
Epoch 6/50
98999/98999 [==============================] - 31s 317us/step - loss: 0.3776 - accuracy: 0.8331 - val_loss: 0.3762 - val_accuracy: 0.8339
Epoch 7/50
98999/98999 [==============================] 

In [0]:
model.save('model.h5')

In [0]:
import sklearn.metrics as m


In [0]:
label_pred=model.predict(feature_test)

In [0]:
label_pred=np.argmax(label_pred,axis=1)

In [181]:
label_pred

array([1, 1, 1, ..., 0, 0, 0])

In [0]:
l_test=np.argmax(label_test,axis=1)

In [183]:
m.accuracy_score(l_test,label_pred)

0.8865454545454545

In [184]:
print(m.classification_report(l_test,label_pred))

              precision    recall  f1-score   support

           0       0.91      0.90      0.91      6726
           1       0.85      0.86      0.85      4274

    accuracy                           0.89     11000
   macro avg       0.88      0.88      0.88     11000
weighted avg       0.89      0.89      0.89     11000



In [185]:
m.confusion_matrix(l_test,label_pred)

array([[6074,  652],
       [ 596, 3678]])

In [0]:
from keras.models import load_model

In [0]:
import pickle

In [0]:
pickle.dump(tokenizer,open('tokenizer.pkl','wb+'),protocol=pickle.HIGHEST_PROTOCOL)

In [0]:
tokenizer=pickle.load(open('tokenizer.pkl','rb+'))

In [171]:
tokenizer.index_word

{1: 'a',
 2: 'e',
 3: 'n',
 4: 'i',
 5: 'r',
 6: 'l',
 7: 's',
 8: 'h',
 9: 't',
 10: 'o',
 11: 'y',
 12: 'm',
 13: 'd',
 14: 'k',
 15: 'u',
 16: 'c',
 17: 'j',
 18: 'b',
 19: 'v',
 20: 'g',
 21: 'z',
 22: 'p',
 23: 'w',
 24: 'f',
 25: 'q',
 26: 'x'}

In [0]:
def input(n):
  q=tokenizer.texts_to_sequences(n)
  q=[i[0] for i in q]
  q1=[]
  q1.append(q)
  s=pad_sequences(q1,maxlen=15,padding='post')
  return s

In [189]:
tokenizer.texts_to_sequences('kamesh')

[[14], [1], [12], [2], [7], [8]]

In [191]:
input('kamesh')

array([[14,  1, 12,  2,  7,  8,  0,  0,  0,  0,  0,  0,  0,  0,  0]],
      dtype=int32)

In [0]:
def pred(n):
  w=model.predict(input(n))
  w=np.argmax(w,axis=1)
  return w[0]

In [203]:
pred('kamesh')

1

In [204]:
pred('rajesh')

1

In [205]:
pred('sudha')

0

In [207]:
pred('srihasa')

0

In [209]:
pred('Alex')

1

In [210]:
pred('preethi')

0

In [211]:
pred('John')

0

In [212]:
pred('mahesh')

1

In [213]:
pred('raju')

1

In [214]:
pred('abhitha')

1

In [215]:
pred('ratnamahadevi')

0

In [216]:
pred('srimukhi')

0

In [218]:
pred('rajashekhar')

1

In [219]:
pred('manga')

0

In [220]:
pred('katyayani')

0

In [221]:
pred('prakash')

1

In [222]:
pred('shanmukh')

1

In [223]:
pred('bhargav')

1

In [224]:
pred('aditya')

1

In [225]:
pred('akshar')

1

In [226]:
pred('madhav')

1

In [227]:
pred('madhavi')

0

In [228]:
pred('durga')

0

In [230]:
pred('saisudha')

0

In [233]:
pred('durgesh')

1

In [237]:
pred('rangesh')

1

In [238]:
pred('rangarao')

1

In [240]:
pred('kameshwari')

0

In [241]:
pred('kameswararao')

1

In [0]:
model.save('model.h5')

In [243]:
pred('srilekha')

0

In [244]:
pred('srikhar')

1