In [2]:
cd /content/drive/My Drive/Gender Classification

/content/drive/My Drive/Gender Classification


In [0]:
!unzip 13_7651_compressed_NationalNames.csv.zip

Archive:  13_7651_compressed_NationalNames.csv.zip
replace NationalNames.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: n


In [1]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
import numpy as np
import pandas as pd


In [0]:
dataset1=pd.read_csv('NationalNames.csv')
dataset2=pd.read_csv('name.csv')
dataset3=pd.read_csv('indiannames.csv')
dataset4=pd.read_csv('nam.csv')
dataset5=pd.read_csv('SSA_Names.csv')

In [0]:
dataset1=dataset1.loc[:,['Name','Gender']]
dataset2=dataset2.loc[:,['Name','Gender']]
dataset3=dataset3.loc[:,['Name','Gender']]
dataset4=dataset4.loc[:,['Name','Gender']]
dataset5=dataset5.loc[:,['Name','Gender']]



In [0]:
data=pd.concat([dataset1,dataset2,dataset3,dataset4,dataset5])

In [0]:
data=data.reset_index()

In [0]:
dataset=data.drop(['index'],axis=1)

In [9]:
dataset

Name Gender
0             Mary      F
1             Anna      F
2             Emma      F
3        Elizabeth      F
4           Minnie      F
...            ...    ...
1994026     Zykell      M
1994027     Zyking      M
1994028      Zykir      M
1994029      Zyrus      M
1994030       Zyus      M

[1994031 rows x 2 columns]

In [10]:
len(dataset['Name'].unique())

110000

In [0]:
dataset.drop_duplicates('Name',ignore_index=True,inplace=True)

In [12]:
dataset.isnull().values.any()

True

In [0]:
dataset=dataset.dropna()

In [14]:
dataset.isnull().values.any()

False

In [0]:
name=dataset['Name']

In [16]:
len(name.unique())

109999

In [0]:
name=list(name)

In [0]:
label=list(dataset['Gender'])

In [19]:
label

['F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F'

In [0]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [0]:
labels=le.fit_transform(label)

In [22]:
labels

array([0, 0, 0, ..., 0, 0, 0])

In [23]:
le.classes_

array(['F', 'M'], dtype='<U1')

In [0]:
from sklearn.feature_extraction.text import CountVectorizer

In [0]:
cv=CountVectorizer(analyzer='char')

In [0]:
names=cv.fit_transform(name).toarray()

In [27]:
len(names[1])

26

In [0]:
from sklearn.model_selection import train_test_split
feature_train,feature_test,label_train,label_test=train_test_split(names,labels,test_size=0.2,random_state=42)

In [29]:
from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB()
model.fit(feature_train,label_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [0]:
label_pred=model.predict(feature_test)

In [0]:
import sklearn.metrics as m

In [32]:
m.accuracy_score(label_test,label_pred)

0.6785909090909091

LSTM

In [33]:
from keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer(char_level=True)
tokenizer.fit_on_texts(name)
sequence_of_int = tokenizer.texts_to_sequences(name)


Using TensorFlow backend.


In [0]:
from keras.preprocessing.sequence import pad_sequences
padsequences=pad_sequences(sequence_of_int,maxlen=15,padding='post')

In [35]:
len(padsequences[2])

15

In [0]:
from keras.utils.np_utils import to_categorical
labels=to_categorical(labels)

In [0]:
from keras.models import Sequential
from keras.layers import Dense,LSTM,Embedding,Dropout

In [38]:
padsequences.shape

(109999, 15)

In [0]:
from sklearn.model_selection import train_test_split
feature_train,feature_test,label_train,label_test=train_test_split(padsequences,labels,test_size=0.1,random_state=42)

In [97]:
model=Sequential()
model.add(Embedding(27,64,input_length=15))
model.add(LSTM(2048,return_sequences=True))
model.add(LSTM(256,return_sequences=False))
model.add(Dropout(0.2))
model.add(Dense(2,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_2 (Embedding)      (None, 15, 64)            1728      
_________________________________________________________________
lstm_3 (LSTM)                (None, 15, 2048)          17309696  
_________________________________________________________________
lstm_4 (LSTM)                (None, 256)               2360320   
_________________________________________________________________
dropout_2 (Dropout)          (None, 256)               0         
_________________________________________________________________
dense_2 (Dense)              (None, 2)                 514       
Total params: 19,672,258
Trainable params: 19,672,258
Non-trainable params: 0
_________________________________________________________________


In [98]:
model.fit(feature_train,label_train,epochs=50,validation_data=(feature_test,label_test),batch_size=1000)


/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/indexed_slices.py:434: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "


Train on 98999 samples, validate on 11000 samples
Epoch 1/50
98999/98999 [==============================] - 32s 324us/step - loss: 0.5722 - accuracy: 0.6994 - val_loss: 0.4984 - val_accuracy: 0.7642
Epoch 2/50
98999/98999 [==============================] - 31s 317us/step - loss: 0.4411 - accuracy: 0.7991 - val_loss: 0.4129 - val_accuracy: 0.8115
Epoch 3/50
98999/98999 [==============================] - 31s 317us/step - loss: 0.4086 - accuracy: 0.8170 - val_loss: 0.4042 - val_accuracy: 0.8210
Epoch 4/50
98999/98999 [==============================] - 31s 317us/step - loss: 0.3995 - accuracy: 0.8219 - val_loss: 0.3927 - val_accuracy: 0.8252
Epoch 5/50
98999/98999 [==============================] - 31s 317us/step - loss: 0.3879 - accuracy: 0.8272 - val_loss: 0.3954 - val_accuracy: 0.8244
Epoch 6/50
98999/98999 [==============================] - 31s 317us/step - loss: 0.3817 - accuracy: 0.8314 - val_loss: 0.3874 - val_accuracy: 0.8259
Epoch 7/50
98999/98999 [==============================] 

In [0]:
model.save('model.h5')

In [0]:
import sklearn.metrics as m


In [0]:
label_pred=model.predict(feature_test)

In [0]:
label_pred=np.argmax(label_pred,axis=1)

In [103]:
label_pred

array([1, 1, 1, ..., 0, 0, 0])

In [0]:
l_test=np.argmax(label_test,axis=1)

In [105]:
m.accuracy_score(l_test,label_pred)

0.8908181818181818

In [106]:
print(m.classification_report(l_test,label_pred))

              precision    recall  f1-score   support

           0       0.91      0.91      0.91      6726
           1       0.86      0.86      0.86      4274

    accuracy                           0.89     11000
   macro avg       0.88      0.89      0.89     11000
weighted avg       0.89      0.89      0.89     11000



In [107]:
m.confusion_matrix(l_test,label_pred)

array([[6108,  618],
       [ 583, 3691]])

In [0]:
from keras.models import load_model

In [0]:
import pickle

In [0]:
pickle.dump(tokenizer,open('tokenizer.pkl','wb+'),protocol=pickle.HIGHEST_PROTOCOL)

In [0]:
tokenizer=pickle.load(open('tokenizer.pkl','rb+'))

In [112]:
tokenizer.index_word

{1: 'a',
 2: 'e',
 3: 'n',
 4: 'i',
 5: 'r',
 6: 'l',
 7: 's',
 8: 'h',
 9: 't',
 10: 'o',
 11: 'y',
 12: 'm',
 13: 'd',
 14: 'k',
 15: 'u',
 16: 'c',
 17: 'j',
 18: 'b',
 19: 'v',
 20: 'g',
 21: 'z',
 22: 'p',
 23: 'w',
 24: 'f',
 25: 'q',
 26: 'x'}

In [0]:
def input(n):
  q=tokenizer.texts_to_sequences(n)
  q=[i[0] for i in q]
  q1=[]
  q1.append(q)
  s=pad_sequences(q1,maxlen=15,padding='post')
  return s

In [114]:
tokenizer.texts_to_sequences('kamesh')

[[14], [1], [12], [2], [7], [8]]

In [115]:
input('kamesh')

array([[14,  1, 12,  2,  7,  8,  0,  0,  0,  0,  0,  0,  0,  0,  0]],
      dtype=int32)

In [0]:
def pred(n):
  w=model.predict(input(n))
  w=np.argmax(w,axis=1)
  return w[0]

In [117]:
pred('kamesh')

1

In [118]:
pred('rajesh')

1

In [119]:
pred('sudha')

0

In [120]:
pred('srihasa')

0

In [121]:
pred('alex')

1

In [122]:
pred('preethi')

0

In [123]:
pred('John')

0

In [124]:
pred('mahesh')

1

In [125]:
pred('raju')

1

In [126]:
pred('abhitha')

0

In [127]:
pred('ratnamahadevi')

0

In [128]:
pred('srimukhi')

1

In [129]:
pred('rajashekhar')

1

In [130]:
pred('manga')

0

In [131]:
pred('katyayani')

0

In [132]:
pred('prakash')

1

In [138]:
pred('shanmukh')

0

In [139]:
pred('bhargav')

1

In [140]:
pred('aditya')

1

In [141]:
pred('akshar')

1

In [142]:
pred('madhav')

1

In [143]:
pred('madhavi')

0

In [144]:
pred('durga')

0

In [145]:
pred('saisudha')

0

In [146]:
pred('durgesh')

1

In [147]:
pred('rangesh')

1

In [148]:
pred('rangarao')

1

In [149]:
pred('kameshwari')

0

In [150]:
pred('kameswararao')

1

In [0]:
model.save('model.h5')

In [152]:
pred('srilekha')

0

In [153]:
pred('srikhar')

1

In [154]:
pred('aliabhatt')

0

In [156]:
pred('aryabatt')

1

In [160]:
pred('harsh')

1

In [161]:
pred('garimasingh')

0

In [164]:
pred('prabhkiratsingh')

1

In [165]:
pred('rakesh')

1

In [166]:
pred('uday')

1

In [167]:
pred('krishna')

1

In [168]:
pred('ram')

1

In [170]:
pred('satyasai')

1

In [171]:
pred('divyansh')

1

In [172]:
pred('anushka')

0

In [173]:
pred('kajol')

0

In [174]:
pred('rithvik')

1

In [175]:
pred('AlamKhan')

1

In [176]:
pred('revathi')

0

In [177]:
pred('deepika')

0

In [178]:
pred('bunty')

1

In [180]:
pred('pandu')

1